spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: product
              uri: lb://PRODUCT
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1